apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harness-app
  template:
    metadata:
      labels:
        app: harness-app
    spec:
      containers:
        - name: harness-app
          image: aristematic/harness:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: harness-svc
  namespace: default
spec:
  selector:
    app: harness-app
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
